<?php   
# WL: For Debugging
// error_reporting( -1 );
// ini_set( 'display_errors', 1 );

# This file was automatically generated by the MediaWiki 1.31.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "測試百科";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";
$wgLoadScript = "{$wgScriptPath}/load.php";
$wgScriptExtension = ".php";
$wgArticlePath = "/wiki/$1";
$wgUsePathInfo = true;

## The protocol and server name to use in fully-qualified URLs
#$wgServer = "https://wikidecode.org";
$wgServer = "http://54.149.203.11";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/resources/assets/wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@pediainside.com";
$wgPasswordSender = "apache@pediainside.com";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "127.0.0.1";
$wgDBname = "mediawikidb";
$wgDBuser = "root";
$wgDBpassword = "hufaBEAR0911";

# MySQL specific settings
$wgDBprefix = "";
$wgSQLMode = null;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

## Shared memory settings
#$wgUseGzip = true;
$wgEnableSidebarCache = true;
$wgMainCacheType = CACHE_MEMCACHED;
$wgParserCacheType = CACHE_MEMCACHED; # optional
$wgMessageCacheType = CACHE_MEMCACHED; # optional
$wgMemCachedServers = array( "127.0.0.1:11211" );
#$wgUseLocalMessageCache = true;
$wgSessionsInObjectCache = true; # optional
$wgSessionCacheType = CACHE_MEMCACHED; # optional

# File cache
$wgUseFileCache = true;
#$wgFileCacheDirectory = "/var/www/mediawiki/file-cache";
$wgFileCacheDirectory = "$IP/cache";

# NO DB HITS!
$wgDisableCounters = true;
$wgMiserMode = true;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
$wgCacheDirectory = "$IP/cache";

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgGenerateThumbnailOnParse = false;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "C.UTF-8";


# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "zh";

$wgSecretKey = "5aeaee8c4b287cbaaa68c692276e70915eab6de03af0f2b18575f347773877f1";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "3e841cd06fe3d3d9";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "minerva";
#$wgDefaultSkin = "bootstrapmediawiki";
#require_once( "$IP/skins/bootstrap-mediawiki/bootstrap-mediawiki.php" );

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );
wfLoadSkin( 'Tweeki' );
wfLoadSkin( 'BlueSky' );
#wfLoadSkin( 'bootstrap-mediawiki' );
//wfLoadSkin( 'Tweeki2' );


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtensions('ExtensionName');
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CiteThisPage' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'LocalisationUpdate' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'OATHAuth' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'Renameuser' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'SpamBlacklist' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TitleBlacklist' );
wfLoadExtension( 'Babel' );

wfLoadExtension( 'cldr' );

wfLoadExtension( 'CleanChanges' );
$wgCCTrailerFilter = true;
$wgCCUserFilter = false;
$wgDefaultUserOptions['usenewrc'] = 1;

wfLoadExtension( 'LocalisationUpdate' );
$wgLocalisationUpdateDirectory = "$IP/cache";

require_once "$IP/extensions/Translate/Translate.php";
$wgGroupPermissions['user']['translate'] = true;
$wgGroupPermissions['user']['translate-messagereview'] = true;
$wgGroupPermissions['user']['translate-groupreview'] = true;
$wgGroupPermissions['user']['translate-import'] = true;
$wgGroupPermissions['sysop']['pagetranslation'] = true;
$wgGroupPermissions['sysop']['translate-manage'] = true;
$wgTranslateDocumentationLanguageCode = 'qqq';
$wgExtraLanguageNames['qqq'] = 'Message documentation'; # No linguistic content. Used for documenting messages

wfLoadExtension( 'UniversalLanguageSelector' );
wfLoadExtension( 'WikiEditor' );

wfLoadExtension( 'Scribunto' );
// wfLoadExtension( 'luasandbox' );
$wgScribuntoDefaultEngine = 'luastandalone';
$wgScribuntoEngineConf['luastandalone']['cpuLimit'] = 'ulimit';
$wgScribuntoEngineConf['luastandalone']['memoryLimit'] = 209715200; # bytes
// $wgScribuntoDefaultEngine = 'luasandbox';
// $wgScribuntoEngineConf['luasandbox']['cpuLimit'] = 'ulimit';
// $wgScribuntoEngineConf['luasandbox']['memoryLimit'] = 209715200; # bytes

wfLoadExtension( 'Nuke' );

wfLoadExtension( 'VisualEditor' );
// Enable by default for everybody
# $wgDefaultUserOptions['visualeditor-enable'] = 1;

// Optional: Set VisualEditor as the default for anonymous users
// otherwise they will have to switch to VE
# $wgDefaultUserOptions['visualeditor-editor'] = "visualeditor";

// Don't allow users to disable it
# $wgHiddenPrefs[] = 'visualeditor-enable';

# Parsoid fir Visual Editor

$wgVirtualRestConfig['modules']['parsoid'] = array(
    // URL to the Parsoid instance
    // Use port 8142 if you use the Debian package
    //'url' => 'http://wikidecode.org:8142',
    'url' => 'http://54.201.235.45:8142',
    // Parsoid "domain", see below (optional)
    //'domain' => 'localhost',
    // Parsoid "prefix", see below (optional)
    //'prefix' => 'localhost'
);

# Wikibase
$wgEnableWikibaseRepo = true;
$wgEnableWikibaseClient = true;
require_once "$IP/extensions/Wikibase/repo/Wikibase.php";
require_once "$IP/extensions/Wikibase/repo/ExampleSettings.php";
require_once "$IP/extensions/Wikibase/client/WikibaseClient.php";
require_once "$IP/extensions/Wikibase/client/ExampleSettings.php";

# Mobile responsive display
wfLoadExtension( 'MobileFrontend' );
$wgMFAutodetectMobileView = true;

wfLoadSkin( 'MinervaNeue' );
$wgMFDefaultSkinClass = 'SkinMinerva';
# End of automatically generated settings.
# Add more configuration options below.
# Auto confirm threshold
$wgAutoConfirmCount=20;

# Tidy # Fix the problem that infobox will show <td? </td>
$wgUseTidy=true;

# Permission (need to comment out to make Visual Editor work)
#$wgGroupPermissions['*']['read'] = false;  # Disable reading by anonymous users
#$wgGroupPermissions['*']['createaccount'] = false;  # Prevent new user registrations except by sysops

# Debugging
$wgShowExceptionDetails = false;
$wgShowDBErrorBacktrace = false;

$wgShowSQLErrors = false;
$wgDebugDumpSql = false;

$wgDebugComments = false;
$wgDebugLogFile = "/var/www/log/debug.log";

$wgPFEnableStringFunctions = true;
$wgMaxShellMemory = 204800; # in KB

# TemplateStyle
wfLoadExtension( 'TemplateStyles' );

#Youtube
wfLoadExtension( 'YouTube' );

#Embedded Video
wfLoadExtension( 'EmbedVideo' );

#Embedded Anything
require_once "$IP/extensions/EmbedAnything/EmbedAnything.php";

# Permission to Hide history
$wgGroupPermissions['sysop']['deletelogentry'] = true;
$wgGroupPermissions['sysop']['deleterevision'] = true;

# Notice 
# $wgSiteNotice = "Internal..."

# Upload picture option
# allow upload by URL
$wgAllowCopyUploads = true;
$wgCopyUploadsFromSpecialUpload = true;

# Increase Session timeout
$wgCookieExpiration = 86400;
$wgExtendedLoginCookieExpiration = null;


# Proxy WWW
#$wgUseSquid = true;
#$wgSquidServers = [ '13.66.203.243' ];
#$wgSquidServersNoPurge = [ '127.0.0.1' ];

# 貢獻得分
require_once "$IP/extensions/ContributionScores/ContributionScores.php";
$wgContribScoreIgnoreBots = true;          // Exclude Bots from the reporting - Can be omitted.
$wgContribScoreIgnoreBlockedUsers = true;  // Exclude Blocked Users from the reporting - Can be omitted.
$wgContribScoresUseRealName = true;        // Use real user names when available - Can be omitted. Only for MediaWiki 1.19 and later.
$wgContribScoreDisableCache = false;       // Set to true to disable cache for parser function and inclusion of table.

//Each array defines a report - 7,50 is "past 7 days" and "LIMIT 50" - Can be omitted.
$wgContribScoreReports = array(
    array(7,20),
    array(30,20),
    array(0,20));

# Change default user behavior
## Add pages the user edits to their watchlist by default
$wgDefaultUserOptions['watchdefault'] = 0;  // 不將更改的page加入監視列表

# 允許外部連結顯示圖片
$wgAllowExternalImages=true;

# 開啟濫用日誌
wfLoadExtension( 'AbuseFilter' );
$wgGroupPermissions['sysop']['abusefilter-modify'] = true;
$wgGroupPermissions['*']['abusefilter-log-detail'] = true;
##$wgGroupPermissions['*']['abusefilter-view'] = true;
##$wgGroupPermissions['*']['abusefilter-log'] = true;
$wgGroupPermissions['sysop']['abusefilter-private'] = true;
$wgGroupPermissions['sysop']['abusefilter-modify-restricted'] = true;
$wgGroupPermissions['sysop']['abusefilter-revert'] = true;

# 防止用戶名使用非格式化字串
#wfLoadExtension( 'AntiSpoof' );
#$wgSharedTables[] = 'spoofuser';

# 允許HTML img tag
$wgAllowImageTag=true;

# 必須email驗證
#$wgEmailConfirmToEdit=true;

# Lockdown Permission
wfLoadExtension( 'Lockdown' );
// WL $wgNamespacePermissionLockdown[NS_TEMPLATE]['*'] = ['bureaucrat'];
$wgNamespacePermissionLockdown[NS_TEMPLATE]['*'] = ['sysop'];
$wgNamespacePermissionLockdown[NS_TEMPLATE]['read'] = ['*'];

# 網站維護....
#$wgReadOnly = 'Dumping Database, Access will be restored shortly';

# 打開舉報 (註冊用戶可以舉報，管理員處理)
wfLoadExtension( 'Report' );

# 可以看見誰正在監視那個page
wfLoadExtension( 'WhoIsWatching' );
$whoiswatching_nametype = "RealName";
# $wgGroupPermissions['sysop']['addpagetoanywatchlist'] = true;
# $wgGroupPermissions['sysop']['seepagewatchers'] = true;

# 追蹤某個使用者的進出狀況
#require_once "$IP/extensions/StalkerLog/StalkerLog.php";
#$wgGroupPermissions['*']['stalkerlog-view-log'] = false;
#$wgGroupPermissions['sysop']['stalkerlog-view-log'] = true;

# Who is online
wfLoadExtension( 'WhosOnline' );
$wgWhosOnlineShowAnons = true;

# 關閉page view counter
# $wgDisableCounters = true;

#wfLoadExtension( 'MatomoAnalytics' );
#$wgMatomoAnalyticsServerURL=false;
#$wgMatomoAnalyticsTokenAuth=false;

wfLoadExtension( 'CheckUser' );
$wgGroupPermissions['sysop']['checkuser'] = true;
#$wgGroupPermissions['sysop']['checkuser-log'] = true;
$wgAddGroups['bureaucrat'][] = 'checkuser';
$wgRemoveGroups['bureaucrat'][] = 'checkuser';


# Local S3 for image
# https://github.com/edwardspec/mediawiki-aws-s3
#wfLoadExtension( 'AWS' );

// Configure AWS credentials.
// THIS IS NOT NEEDED if your EC2 instance has an IAM instance profile.
#$wgAWSCredentials = [
#	'key' => 'AKIAJELD4SFIX5N6U7PA',
#	'secret' => '5fFfbfAqhXYh0WMNZw+alif7zTd59xPC0ygMQxIN',
#	'token' => false
#];

#$wgAWSRegion = 'us-west-2'; # Oregon

// Replace <something> with the name of your S3 bucket, e.g. wonderfulbali234.
#$wgAWSBucketName = "s3mediawiki";
#$wgUploadDirectory = "$IP/s3mnt";
#$wgUploadPath = "$wgScriptPath/s3mnt";

# Anti-Robot Mechanism
wfLoadExtension( 'ConfirmEdit' );
#$wgGroupPermissions['*'            ]['skipcaptcha'] = false; // Default
#$wgGroupPermissions['user'         ]['skipcaptcha'] = false; // Default
#$wgGroupPermissions['autoconfirmed']['skipcaptcha'] = false; // Default
#$wgGroupPermissions['bot'          ]['skipcaptcha'] = true;  // Default: registered bots
#$wgGroupPermissions['sysop'        ]['skipcaptcha'] = true;  // Default


$wgCaptchaTriggers['edit'] = false;            // Trigger while editing a page
#$wgCaptchaTriggers['create'] = true;          // Default: Trigger while creating a page
#$wgCaptchaTriggers['addurl'] = true;          // Default: Trigger while ading a url
#$wgCaptchaTriggers['createaccount'] = true;   // Default: Trigger while registering
#$wgCaptchaTriggers['badlogin'] = true;        // Default: Trigger while bad login

//gadgets
$wgGroupPermissions['sysop']['gadgets-edit'] = true;
$wgGroupPermissions['sysop']['gadgets-definition-edit'] = true;

$wgDebugLogGroups = array(
	'ContributionScores' => '/var/www/mediawiki/debug1.log'
);

wfLoadExtension( 'PageTriage' );

wfLoadExtension( 'Echo' );

#wfLoadExtension( 'ArticleCreationWorkflow' );

wfLoadExtension( 'RelatedArticles' );
$wgRelatedArticlesFooterWhitelistedSkins = ['vector'];

//Search
wfLoadExtension( 'Elastica' );

//!!!!!!! this have to at bottom !!!!!!!!

$wgDisableSearchUpdate = true;
$wgCirrusSearchServers = [ 'elasticsearch0', 'elasticsearch1', 'elasticsearch2', 'elasticsearch3' ];

require_once "$IP/extensions/CirrusSearch/CirrusSearch.php";
#require_once( "$IP/skins/bootstrap-mediawiki/bootstrap-mediawiki.php" );
